### ISSUE TITLE
CodeGen error after deleting SQL table

### ISSUE THREAD

**Issue by HiteshDhamecha** [MemberJunction/MJ#207]
Hello @hiltongr,

**Describe the bug**
After deleting an SQL table and running CodeGen throws errors.

**To Reproduce**
1. Create a table
2. Run CodeGen
3. Delete a table
4. Run CodeGen again

**Logs**

```
serverName: 'DESKTOP-XXXXXXX',
    procName: 'vwXYZs',
    precedingErrors: []
  },
  code: 'EREQUEST',
  originalError: Error: Invalid object name 'dbo.XYZ'.
      at handleError (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\mssql\lib\tedious\request.js:382:19)
      at Connection.emit (node:events:514:28)
      at Connection.emit (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\connection.ts:1902:18)
      at RequestTokenHandler.onErrorMessage (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\handler.ts:388:21)
      at Readable.<anonymous> (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\token-stream-parser.ts:22:55)
      at Readable.emit (node:events:514:28)
      at addChunk (node:internal/streams/readable:545:12)
      at readableAddChunkPushObjectMode (node:internal/streams/readable:521:3)
      at Readable.push (node:internal/streams/readable:376:5)
      at next (node:internal/streams/from:98:31) {
    info: ErrorMessageToken {
      name: 'ERROR',
      handlerName: 'onErrorMessage',
      number: 208,
      state: 1,
      class: 16,
      message: "Invalid object name 'dbo.XYZ'.",
      serverName: 'DESKTOP-XXXXXXX',
      procName: 'vwXYZs',
      lineNumber: 8
    }
  },
  number: 208,
  lineNumber: 8,
  state: 1,
  class: 16,
  serverName: 'DESKTOP-XXXXXXX',
  procName: 'vwXYZs',
  precedingErrors: []
}
QueryFailedError: Error: Cannot find the object 'vwXYZs', because it does not exist or you do not have permission.
    at C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\src\driver\sqlserver\SqlServerQueryRunner.ts:282:30      
    at C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\mssql\lib\base\request.js:440:25
    at Request.userCallback (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\mssql\lib\tedious\request.js:492:15)
    at Request.callback (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\request.ts:379:14)
    at Parser.onEndOfMessage (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\connection.ts:3713:22)
    at Object.onceWrapper (node:events:628:28)
    at Parser.emit (node:events:514:28)
    at Readable.<anonymous> (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\token-stream-parser.ts:30:12)
    at Readable.emit (node:events:514:28)
    at endReadableNT (node:internal/streams/readable:1589:12) {
  query: '\n' +
    'GRANT SELECT ON [dbo].[vwXYZs] TO [cdp_UI], [cdp_Developer], [cdp_Integration]\n' +
    '    ',
  parameters: undefined,
  driverError: RequestError: Cannot find the object 'vwXYZs', because it does not exist or you do not have permission.
      at handleError (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\mssql\lib\tedious\request.js:384:15)
      at Connection.emit (node:events:514:28)
      at Connection.emit (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\connection.ts:1902:18)
      at RequestTokenHandler.onErrorMessage (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\handler.ts:388:21)
      at Readable.<anonymous> (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\token-stream-parser.ts:22:55)
      at Readable.emit (node:events:514:28)
      at addChunk (node:internal/streams/readable:545:12)
      at readableAddChunkPushObjectMode (node:internal/streams/readable:521:3)
      at Readable.push (node:internal/streams/readable:376:5)
      at next (node:internal/streams/from:98:31) {
    code: 'EREQUEST',
    originalError: Error: Cannot find the object 'vwXYZs', because it does not exist or you do not have permission.
        at handleError (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\mssql\lib\tedious\request.js:382:19)
        at Connection.emit (node:events:514:28)
        at Connection.emit (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\connection.ts:1902:18)
        at RequestTokenHandler.onErrorMessage (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\handler.ts:388:21)
        at Readable.<anonymous> (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\token-stream-parser.ts:22:55)
        at Readable.emit (node:events:514:28)
        at addChunk (node:internal/streams/readable:545:12)
        at readableAddChunkPushObjectMode (node:internal/streams/readable:521:3)
        at Readable.push (node:internal/streams/readable:376:5)
        at next (node:internal/streams/from:98:31) {
      info: [ErrorMessageToken]
    },
    number: 15151,
    lineNumber: 2,
    state: 1,
    class: 16,
    serverName: 'DESKTOP-XXXXXXX',
    procName: '',
    precedingErrors: []
  },
  code: 'EREQUEST',
  originalError: Error: Cannot find the object 'vwXYZs', because it does not exist or you do not have permission.
      at handleError (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\mssql\lib\tedious\request.js:382:19)
      at Connection.emit (node:events:514:28)
      at Connection.emit (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\connection.ts:1902:18)
      at RequestTokenHandler.onErrorMessage (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\handler.ts:388:21)
      at Readable.<anonymous> (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\token-stream-parser.ts:22:55)
      at Readable.emit (node:events:514:28)
      at addChunk (node:internal/streams/readable:545:12)
      at readableAddChunkPushObjectMode (node:internal/streams/readable:521:3)
      at Readable.push (node:internal/streams/readable:376:5)
      at next (node:internal/streams/from:98:31) {
    info: ErrorMessageToken {
      name: 'ERROR',
      handlerName: 'onErrorMessage',
      number: 15151,
      state: 1,
      class: 16,
      message: "Cannot find the object 'vwXYZs', because it does not exist or you do not have permission.",
      serverName: 'DESKTOP-XXXXXXX',
      procName: '',
      lineNumber: 2
    }
  },
  number: 15151,
  lineNumber: 2,
  state: 1,
  class: 16,
  serverName: 'DESKTOP-XXXXXXX',
  procName: '',
  precedingErrors: []
}
QueryFailedError: Error: Cannot find the object 'vwXYZs', because it does not exist or you do not have permission.
    at C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\src\driver\sqlserver\SqlServerQueryRunner.ts:282:30      
    at C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\mssql\lib\base\request.js:440:25
    at Request.userCallback (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\mssql\lib\tedious\request.js:492:15)
    at Request.callback (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\request.ts:379:14)
    at Parser.onEndOfMessage (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\connection.ts:3713:22)
    at Object.onceWrapper (node:events:628:28)
    at Parser.emit (node:events:514:28)
    at Readable.<anonymous> (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\token-stream-parser.ts:30:12)
    at Readable.emit (node:events:514:28)
    at endReadableNT (node:internal/streams/readable:1589:12) {
  query: '-----------------------------------------------------------------\n' +
    '-- SQL Code Generation\n' +
    '-- Entity: XYZs\n' +
    '-- Item: Permissions for vwXYZs\n' +
    '-- Generated: 16/5/2024, 7:32:14 pm\n' +
    '--\n' +
    '-- This was generated by the MemberJunction CodeGen tool.\n' +
    '-- This file should NOT be edited by hand.\n' +
    '-----------------------------------------------------------------\n' +
    '\n' +
    'GRANT SELECT ON [dbo].[vwXYZs] TO [cdp_UI], [cdp_Developer], [cdp_Integration]',
  parameters: undefined,
  driverError: RequestError: Cannot find the object 'vwXYZs', because it does not exist or you do not have permission.
      at handleError (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\mssql\lib\tedious\request.js:384:15)
      at Connection.emit (node:events:514:28)
      at Connection.emit (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\connection.ts:1902:18)
      at RequestTokenHandler.onErrorMessage (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\handler.ts:388:21)
      at Readable.<anonymous> (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\token-stream-parser.ts:22:55)
      at Readable.emit (node:events:514:28)
      at addChunk (node:internal/streams/readable:545:12)
      at readableAddChunkPushObjectMode (node:internal/streams/readable:521:3)
      at Readable.push (node:internal/streams/readable:376:5)
      at next (node:internal/streams/from:98:31) {
    code: 'EREQUEST',
    originalError: Error: Cannot find the object 'vwXYZs', because it does not exist or you do not have permission.
        at handleError (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\mssql\lib\tedious\request.js:382:19)
        at Connection.emit (node:events:514:28)
        at Connection.emit (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\connection.ts:1902:18)
        at RequestTokenHandler.onErrorMessage (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\handler.ts:388:21)
        at Readable.<anonymous> (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\token-stream-parser.ts:22:55)
        at Readable.emit (node:events:514:28)
        at addChunk (node:internal/streams/readable:545:12)
        at readableAddChunkPushObjectMode (node:internal/streams/readable:521:3)
        at Readable.push (node:internal/streams/readable:376:5)
        at next (node:internal/streams/from:98:31) {
      info: [ErrorMessageToken]
    },
    number: 15151,
    lineNumber: 11,
    state: 1,
    class: 16,
    serverName: 'DESKTOP-XXXXXXX',
    procName: '',
    precedingErrors: []
  },
  code: 'EREQUEST',
  originalError: Error: Cannot find the object 'vwXYZs', because it does not exist or you do not have permission.
      at handleError (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\mssql\lib\tedious\request.js:382:19)
      at Connection.emit (node:events:514:28)
      at Connection.emit (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\connection.ts:1902:18)
      at RequestTokenHandler.onErrorMessage (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\handler.ts:388:21)
      at Readable.<anonymous> (C:\xxxxxxx\MJ\MemberJunction_1.2.2\MemberJunction_Code_Bootstrap_2024_05_02T19_58\CodeGen\node_modules\tedious\src\token\token-stream-parser.ts:22:55)
      at Readable.emit (node:events:514:28)
      at addChunk (node:internal/streams/readable:545:12)
      at readableAddChunkPushObjectMode (node:internal/streams/readable:521:3)
      at Readable.push (node:internal/streams/readable:376:5)
      at next (node:internal/streams/from:98:31) {
    info: ErrorMessageToken {
      name: 'ERROR',
      handlerName: 'onErrorMessage',
      number: 15151,
      state: 1,
      class: 16,
      message: "Cannot find the object 'vwXYZs', because it does not exist or you do not have permission.",
      serverName: 'DESKTOP-XXXXXXX',
      procName: '',
      lineNumber: 11
    }
  },
  number: 15151,
  lineNumber: 11,
  state: 1,
  class: 16,
  serverName: 'DESKTOP-XXXXXXX',
  procName: '',
  precedingErrors: []
}
```

**Comment by cadam11** [comment]
Duplicates #158
