### ISSUE TITLE
{{UserID}} not replaced in RowLevelSecurityFilter processing

### ISSUE THREAD

**Issue by dray-mc** [MemberJunction/MJ#210]
Using RowLevelSecurityFilters to limit content for specific users based on related records and tried to use the templated field {{UserID}} to get the ID of the current user. It failed with a syntax error because it didn't replace that field before running the SQL. Changed it to {{UserEmail}} and it worked just fine.

Including the full error log, but the key part is:

'\t\tAND uMJ.ID = {{UserID}}\r\n' +
...
driverError: RequestError: Incorrect syntax near '{'.

Just for comparison, when I replaced it with {{UserEmail}} I forgot the single quotes at first and the (expected) error showed SQL with the value replaced:

'\t\tAND uMJ.Email = dray+mraa@tasio.co\r\n' +

You should be able to duplicate this by tying any EntityPermission record to a RowLevelSecurityFilter that uses {{UserID}}.

Absolutely not a critical problem - email is fine and working great, just defaulted to using ID first.

Error log:

QueryFailedError: Error: Incorrect syntax near '{'.
    at C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\typeorm\driver\sqlserver\SqlServerQueryRunner.js:205:30
    at C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\mssql\lib\base\request.js:440:25
    at Request.userCallback (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\mssql\lib\tedious\request.js:492:15)
    at Request.callback (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\tedious\lib\request.js:239:14)
    at Parser.onEndOfMessage (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\tedious\lib\connection.js:2623:22)
    at Object.onceWrapper (node:events:632:28)
    at Parser.emit (node:events:518:28)
    at Readable.<anonymous> (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\tedious\lib\token\token-stream-parser.js:24:12)
    at Readable.emit (node:events:518:28)
    at endReadableNT (node:internal/streams/readable:1696:12) {
  query: 'SELECT TOP 1000 [ID],[OrganizationID],[Key],[Name],[Active],[Domain],[Description],[Organization] FROM [dbo].vwOrganizationKeys WHERE (OrganizationID=37) AND ((OrganizationID IN (\r\n' +
    '\tSELECT ou.OrganizationID\r\n' +
    '\tFROM __mj.[vwUsers] uMJ\r\n' +
    '\t\tJOIN dbo.[vwUsers__dbo] u\r\n' +
    '\t\t\tON uMJ.email = u.UserID\r\n' +
    '\t\tJOIN vwOrganizationUsers ou\r\n' +
    '\t\t\tON u.ID = ou.UserID\r\n' +
    '\t\tJOIN vwOrganizationUserGroups oug\r\n' +
    '\t\t\tON ou.ID = oug.OrganizationUserID\r\n' +
    '\t\tJOIN [vwGroups] g\r\n' +
    '\t\t\tON oug.GroupID = g.ID\r\n' +
    "\tWHERE g.Name = 'Administrators'\r\n" +
    '\t\tAND uMJ.ID = {{UserID}}\r\n' +
    ')))',
  parameters: undefined,
  driverError: RequestError: Incorrect syntax near '{'.
      at handleError (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\mssql\lib\tedious\request.js:384:15)
      at Connection.emit (node:events:518:28)
      at Connection.emit (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\tedious\lib\connection.js:959:18)
      at RequestTokenHandler.onErrorMessage (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\tedious\lib\token\handler.js:285:21)
      at Readable.<anonymous> (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\tedious\lib\token\token-stream-parser.js:18:33)
      at Readable.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
      at Readable.push (node:internal/streams/readable:391:5)
      at nextAsync (node:internal/streams/from:194:22) {
    code: 'EREQUEST',
    originalError: Error: Incorrect syntax near '{'.
        at handleError (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\mssql\lib\tedious\request.js:382:19)
        at Connection.emit (node:events:518:28)
        at Connection.emit (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\tedious\lib\connection.js:959:18)
        at RequestTokenHandler.onErrorMessage (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\tedious\lib\token\handler.js:285:21)
        at Readable.<anonymous> (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\tedious\lib\token\token-stream-parser.js:18:33)
        at Readable.emit (node:events:518:28)
        at addChunk (node:internal/streams/readable:559:12)
        at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
        at Readable.push (node:internal/streams/readable:391:5)
        at nextAsync (node:internal/streams/from:194:22) {
      info: [ErrorMessageToken]
    },
    number: 102,
    lineNumber: 13,
    state: 1,
    class: 15,
    serverName: 'tasio-betty-api',
    procName: '',
    precedingErrors: []
  },
  code: 'EREQUEST',
  originalError: Error: Incorrect syntax near '{'.
      at handleError (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\mssql\lib\tedious\request.js:382:19)
      at Connection.emit (node:events:518:28)
      at Connection.emit (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\tedious\lib\connection.js:959:18)
      at RequestTokenHandler.onErrorMessage (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\tedious\lib\token\handler.js:285:21)
      at Readable.<anonymous> (C:\Users\mcfar\OneDrive\Work\Tasio\TasioSoftware\Code\betty\betty-admin-ui\MJAPI\node_modules\tedious\lib\token\token-stream-parser.js:18:33)
      at Readable.emit (node:events:518:28)
      at addChunk (node:internal/streams/readable:559:12)
      at readableAddChunkPushObjectMode (node:internal/streams/readable:536:3)
      at Readable.push (node:internal/streams/readable:391:5)
      at nextAsync (node:internal/streams/from:194:22) {
    info: ErrorMessageToken {
      name: 'ERROR',
      handlerName: 'onErrorMessage',
      number: 102,
      state: 1,
      class: 15,
      message: "Incorrect syntax near '{'.",
      serverName: 'tasio-betty-api',
      procName: '',
      lineNumber: 13
    }
  },
  number: 102,
  lineNumber: 13,
  state: 1,
  class: 15,
  serverName: 'tasio-betty-api',
  procName: '',
  precedingErrors: []
}

**Comment by AN-BC** [comment]
Resolved. `securityInfo.ts:261-280` implements `MarkupFilterText()` which iterates through all user properties and performs global regex replacement of `{{User*}}` tokens in RLS filters.
